/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.evento;

import control.ControlEvento;
import java.text.ParseException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import view.credenciamento.CadastroCredenciamento;

/**
 *
 * @author Andre Teixeira
 */
public class BuscaEvento extends javax.swing.JInternalFrame {

    ControlEvento control = new ControlEvento();
    CadastroCredenciamento credenciamento;

    /**
     * Creates new form BuscaEvento
     */
    public BuscaEvento() {
        initComponents();
        String busca = JOptionPane.showInputDialog("Digite o texto desejado para ser buscado nos campos de codigo e nome: ");
        inseriLinhaTabela(control.recuperar(busca));
        setName("Buscando por: " + busca.toUpperCase());
    }

    public BuscaEvento(String[][] retornoMatriz) {
        initComponents();
        inseriLinhaTabela(retornoMatriz);
    }

    public BuscaEvento(CadastroCredenciamento cadastroCredenciamento) {
        initComponents();
        this.credenciamento = cadastroCredenciamento;
        String busca = JOptionPane.showInputDialog("Digite o texto desejado para ser buscado nos campos de codigo e nome: ");
        inseriLinhaTabela(control.recuperar(busca));
        setName("Buscando por: " + busca.toUpperCase());
    }

    private void inseriLinhaTabela(String[][] matriz) {
        DefaultTableModel model_tbl_lista = (DefaultTableModel) jTable1.getModel();
        model_tbl_lista.setNumRows(0);
        for (String[] matriz1 : matriz) {
            model_tbl_lista.addRow(new Object[]{matriz1[0],
                matriz1[1],
                matriz1[2],
                matriz1[3],
                matriz1[4],
                matriz1[5],
                matriz1[6],
                matriz1[7]});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tb_lista = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "DESCRIÇÃO", "CAPACIDADE", "ENDEREÇO", "CIDADE", "DATA INICIO", "DATA FIM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_lista.setViewportView(jTable1);

        jButton1.setText("Selecionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(tb_lista, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_lista, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DefaultTableModel model_tbl_lista = (DefaultTableModel) jTable1.getModel();
        int selecao = jTable1.getSelectedRow();
        if (selecao != -1) {
            int codigo = Integer.parseInt( model_tbl_lista.getValueAt(selecao, 0).toString());
            this.credenciamento.preencheTelaEvento(codigo);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um evento antes de prosseguir");
        }
       doDefaultCloseAction();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tb_lista;
    // End of variables declaration//GEN-END:variables
}
