/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.evento;

import control.ControlEvento;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Andre Teixeira
 */
public class CadastroEventos extends javax.swing.JInternalFrame {

    private String[] vetor = new String[9];

    /**
     * Creates new form CadastroEventos
     */
    public CadastroEventos() {
        initComponents();
    }

    public CadastroEventos(int codigo) throws ParseException {
        initComponents();
        if (codigo == 0) {
            lb_codigo.setText(String.valueOf(codigo));
        } else {
            ControlEvento controle = new ControlEvento();
            vetor = controle.recuperar(codigo);

            lb_codigo.setText(vetor[0]);
            lb_nome.setText(vetor[1]);
            lb_descricao.setText(vetor[2]);
            lb_capacidade.setText(vetor[3]);
            lb_endereco.setText(vetor[4]);
            lb_cidade.setText(vetor[5]);
            
            SimpleDateFormat formatSpinner = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy", Locale.US);
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
           
            sp_inicial.setValue(formatSpinner.parse(formatSpinner.format(dateFormat.parse(vetor[6]))));
            sp_final.setValue(formatSpinner.parse(formatSpinner.format(dateFormat.parse(vetor[7]))));
        }
        lb_codigo.setEditable(false);
    }

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_conteudo = new javax.swing.JPanel();
        txt_codigo = new javax.swing.JLabel();
        lb_codigo = new javax.swing.JTextField();
        txt_nome = new javax.swing.JLabel();
        lb_nome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_descricao = new javax.swing.JLabel();
        lb_descricao = new javax.swing.JTextField();
        txt_capacidade = new javax.swing.JLabel();
        lb_capacidade = new javax.swing.JTextField();
        txt_endereco = new javax.swing.JLabel();
        lb_endereco = new javax.swing.JTextField();
        txt_cidade = new javax.swing.JLabel();
        lb_cidade = new javax.swing.JTextField();
        txt_dataInicial = new javax.swing.JLabel();
        txt_data_final = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        sp_inicial = new javax.swing.JSpinner(sm);
        Date datefinal = new Date();
        SpinnerDateModel smfinal = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        sp_final = new javax.swing.JSpinner(smfinal);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        DELETAR = new javax.swing.JMenu();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/event.png"))); // NOI18N

        pn_conteudo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_codigo.setText("CODIGO:");

        txt_nome.setText("* NOME:");

        txt_descricao.setText("DESCRÇÃO");

        txt_capacidade.setText("CAPACIDADE");

        txt_endereco.setText("ENDEREÇO");

        txt_cidade.setText("CIDADE");

        lb_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_cidadeActionPerformed(evt);
            }
        });

        txt_dataInicial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_dataInicial.setText("DATA INICIAL");

        txt_data_final.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_data_final.setText("DATA FINAL");

        JSpinner.DateEditor de =new JSpinner.DateEditor(sp_inicial, "HH:mm:ss");

        JSpinner.DateEditor definal =new JSpinner.DateEditor(sp_inicial, "HH:mm:ss");

        javax.swing.GroupLayout pn_conteudoLayout = new javax.swing.GroupLayout(pn_conteudo);
        pn_conteudo.setLayout(pn_conteudoLayout);
        pn_conteudoLayout.setHorizontalGroup(
            pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pn_conteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_data_final, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pn_conteudoLayout.createSequentialGroup()
                            .addComponent(txt_codigo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lb_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_descricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_descricao, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_capacidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_capacidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_endereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_cidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_dataInicial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                            .addComponent(sp_final, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_endereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp_inicial))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_conteudoLayout.setVerticalGroup(
            pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_conteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codigo)
                    .addComponent(lb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nome)
                    .addComponent(lb_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_data_final, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_final, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/save.png"))); // NOI18N
        jMenu1.setText("SALVAR");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/cancel.png"))); // NOI18N
        jMenu2.setText("CANCELAR");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        DELETAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/delete.png"))); // NOI18N
        DELETAR.setText("DELETAR");
        DELETAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETARMouseClicked(evt);
            }
        });
        jMenuBar1.add(DELETAR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        ControlEvento ctrl = new ControlEvento();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        if (!lb_codigo.getText().equals("")
                && !lb_nome.getText().equals("")
                && !sp_inicial.getValue().toString().equals("")
                && !sp_inicial.getValue().toString().equals("")) {

            vetor[0] = lb_codigo.getText();
            vetor[1] = lb_nome.getText();
            vetor[2] = lb_descricao.getText();
            vetor[3] = lb_capacidade.getText();
            vetor[4] = lb_endereco.getText();
            vetor[5] = lb_cidade.getText();
            try {
                SimpleDateFormat formatSpinner = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy", Locale.US);
                
                vetor[6] = sdf.format(formatSpinner.parse(sp_inicial.getValue().toString()));
                vetor[7] = sdf.format(formatSpinner.parse(sp_final.getValue().toString()));
            } catch (ParseException ex) {
                Logger.getLogger(CadastroEventos.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (vetor[8] == null) {
                vetor[8] = sdf.format(Calendar.getInstance().getTime());
            }

            ctrl.salvar(vetor);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor, Preencha todos os campos!");
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        doDefaultCloseAction();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void DELETARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETARMouseClicked
        ControlEvento ctrl = new ControlEvento();
        ctrl.excluir(Integer.parseInt(lb_codigo.getText()));
        dispose();
    }//GEN-LAST:event_DELETARMouseClicked

    private void lb_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_cidadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DELETAR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lb_capacidade;
    private javax.swing.JTextField lb_cidade;
    private javax.swing.JTextField lb_codigo;
    private javax.swing.JTextField lb_descricao;
    private javax.swing.JTextField lb_endereco;
    private javax.swing.JTextField lb_nome;
    private javax.swing.JPanel pn_conteudo;
    private javax.swing.JSpinner sp_final;
    private javax.swing.JSpinner sp_inicial;
    private javax.swing.JLabel txt_capacidade;
    private javax.swing.JLabel txt_cidade;
    private javax.swing.JLabel txt_codigo;
    private javax.swing.JLabel txt_dataInicial;
    private javax.swing.JLabel txt_data_final;
    private javax.swing.JLabel txt_descricao;
    private javax.swing.JLabel txt_endereco;
    private javax.swing.JLabel txt_nome;
    // End of variables declaration//GEN-END:variables
}
