/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.evento;

import control.ControlEvento;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre Teixeira
 */
public final class ConsultaEventos extends javax.swing.JInternalFrame {

    private String[] usuario;

    /**
     * Creates new form ConsultaEvento
     */
    public ConsultaEventos() {
        inicial();
    }

    public ConsultaEventos(String[] dados) {
        usuario = dados;
        inicial();
        if (!usuario[1].equals("true")) {
            NOVO.setVisible(false);
            EDITAR.setVisible(false);
            DELETAR.setVisible(false);
        }
    }

    public void inicial() {
        initComponents();
        inseriLinhaTabela();
    }

    private void inseriLinhaTabela() {
        ControlEvento control = new ControlEvento();
        String[][] matriz = control.recuperar();

        DefaultTableModel model_tbl_lista = (DefaultTableModel) jTable1.getModel();
        model_tbl_lista.setNumRows(0);
        for (String[] matriz1 : matriz) {
            model_tbl_lista.addRow(new Object[]{matriz1[0],
                matriz1[1],
                matriz1[2],
                matriz1[3],
                matriz1[4],
                matriz1[5],
                matriz1[6],
                matriz1[7]});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tb_lista = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        NOVO = new javax.swing.JMenu();
        EDITAR = new javax.swing.JMenu();
        PROCURAR = new javax.swing.JMenu();
        DELETAR = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eventos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/event.png"))); // NOI18N

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "DESCRIÇÃO", "CAPACIDADE", "ENDEREÇO", "CIDADE", "DATA INICIO", "DATA FIM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_lista.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tb_lista, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tb_lista, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista De Eventos", jPanel1);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NOVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/add.png"))); // NOI18N
        NOVO.setText("NOVO");
        NOVO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOVOMouseClicked(evt);
            }
        });
        jMenuBar1.add(NOVO);

        EDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/edit.png"))); // NOI18N
        EDITAR.setText("EDITAR");
        EDITAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EDITARMouseClicked(evt);
            }
        });
        jMenuBar1.add(EDITAR);

        PROCURAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/search.png"))); // NOI18N
        PROCURAR.setText("PROCURAR");
        PROCURAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROCURARMouseClicked(evt);
            }
        });
        jMenuBar1.add(PROCURAR);

        DELETAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/delete.png"))); // NOI18N
        DELETAR.setText("DELETAR");
        DELETAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETARMouseClicked(evt);
            }
        });
        jMenuBar1.add(DELETAR);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/loop.png"))); // NOI18N
        jMenu1.setText("ATUALIZAR");
        jMenu1.setToolTipText("");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NOVOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOVOMouseClicked
        try {
            CadastroEventos tela = new CadastroEventos(0);
            tela.setVisible(true);
            jTabbedPane1.addTab("Cadastro Pessoa", tela);
            jTabbedPane1.setSelectedComponent(tela);
        } catch (ParseException ex) {
            Logger.getLogger(ConsultaEventos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NOVOMouseClicked

    private void EDITARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITARMouseClicked
        try {
            DefaultTableModel model_tbl_lista = (DefaultTableModel) jTable1.getModel();
            int selecao = jTable1.getSelectedRow();
            if (selecao != -1) {
                int codigo = Integer.parseInt(model_tbl_lista.getValueAt(selecao, 0).toString());
                CadastroEventos tela = new CadastroEventos(codigo);
                tela.setVisible(true);
                jTabbedPane1.addTab("Editando: " + model_tbl_lista.getValueAt(selecao, 1).toString().toUpperCase(), tela);
                jTabbedPane1.setSelectedComponent(tela);
            } else {
                JOptionPane.showMessageDialog(null, "Selecione um evento antes de prosseguir");
            }
        } catch (ParseException ex) {
            Logger.getLogger(ConsultaEventos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EDITARMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        inseriLinhaTabela();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained

    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void DELETARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETARMouseClicked
        DefaultTableModel model_tbl_lista = (DefaultTableModel) jTable1.getModel();
        int selecao = jTable1.getSelectedRow();
        int codigo = Integer.parseInt(model_tbl_lista.getValueAt(selecao, 0).toString());
        ControlEvento ctrl = new ControlEvento();
        ctrl.excluir(codigo);
    }//GEN-LAST:event_DELETARMouseClicked

    private void PROCURARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROCURARMouseClicked
        BuscaEvento tela = new BuscaEvento();
        tela.setVisible(true);
        jTabbedPane1.add(tela);
        jTabbedPane1.setSelectedComponent(tela);
    }//GEN-LAST:event_PROCURARMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DELETAR;
    private javax.swing.JMenu EDITAR;
    private javax.swing.JMenu NOVO;
    private javax.swing.JMenu PROCURAR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tb_lista;
    // End of variables declaration//GEN-END:variables
}
