/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.usuario;

import control.ControlUsuario;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import facade.Criptografia;

/**
 *
 * @author Andre Teixeira
 */
public final class CadastroUsuarios extends javax.swing.JInternalFrame {

    private String[] vetor = new String[6];
    private String[] usuario;
    /**
     * Creates new form Novo_Usuario
     */
    public CadastroUsuarios() {
        initComponents();
    }

    public CadastroUsuarios(int codigo, String[] dados) {
        usuario = dados;
        initComponents();
        if (codigo == 0) {
            lb_codigo.setText(String.valueOf(codigo));
        } else {
            ControlUsuario controle = new ControlUsuario();
            vetor = controle.recuperar(codigo);
            lb_codigo.setText(vetor[0]);
            lb_nome.setText(vetor[1]);
            lb_login.setText(vetor[2]);
            cb_admin.setSelected(Boolean.parseBoolean(vetor[4]));
            if (!usuario[1].equals("true")){
                trocaHabilitar(false);
            }
        }        
        lb_codigo.setEnabled(false);
    }

    public void trocaHabilitar(boolean chave) {
        lb_login.setEnabled(chave);
        cb_admin.setEnabled(chave);
        DELETAR.setVisible(chave);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_conteudo = new javax.swing.JPanel();
        txt_codigo = new javax.swing.JLabel();
        lb_codigo = new javax.swing.JTextField();
        txt_nome = new javax.swing.JLabel();
        lb_nome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_login = new javax.swing.JLabel();
        lb_login = new javax.swing.JTextField();
        txt_senha = new javax.swing.JLabel();
        pss_senha = new javax.swing.JPasswordField();
        cb_admin = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        DELETAR = new javax.swing.JMenu();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/supervisor.png"))); // NOI18N

        pn_conteudo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_codigo.setText("CODIGO:");

        lb_codigo.setEditable(false);

        txt_nome.setText("* NOME:");

        txt_login.setText("LOGIN");

        lb_login.setBackground(new java.awt.Color(255, 255, 255));

        txt_senha.setText("SENHA");

        cb_admin.setText("ADMINISTRADOR?");

        javax.swing.GroupLayout pn_conteudoLayout = new javax.swing.GroupLayout(pn_conteudo);
        pn_conteudo.setLayout(pn_conteudoLayout);
        pn_conteudoLayout.setHorizontalGroup(
            pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pn_conteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lb_login, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pss_senha, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_senha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addComponent(txt_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_conteudoLayout.createSequentialGroup()
                        .addComponent(txt_codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pn_conteudoLayout.setVerticalGroup(
            pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_conteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codigo)
                    .addComponent(txt_nome)
                    .addComponent(lb_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pss_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cb_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/save.png"))); // NOI18N
        jMenu1.setText("SALVAR");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/cancel.png"))); // NOI18N
        jMenu2.setText("CANCELAR");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        DELETAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/delete.png"))); // NOI18N
        DELETAR.setText("DELETAR");
        DELETAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETARMouseClicked(evt);
            }
        });
        jMenuBar1.add(DELETAR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_conteudo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        ControlUsuario ctrl = new ControlUsuario();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            if (!lb_codigo.getText().equals("")
                    && !lb_nome.getText().equals("")
                    && !lb_login.getText().equals("")
                    && !String.valueOf(pss_senha.getPassword()).equals("")) {

                vetor[0] = lb_codigo.getText();
                vetor[1] = lb_nome.getText();
                vetor[2] = lb_login.getText();
                vetor[3] = Criptografia.criptografa(String.copyValueOf(pss_senha.getPassword()));
                vetor[4] = String.valueOf(cb_admin.isSelected());
                if (vetor[5] == null) {
                    vetor[5] = sdf.format(Calendar.getInstance().getTime());
                }
                ctrl.salvar(vetor);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Por Favor, Preencha todos os campos!");
            }
        } catch (NoSuchAlgorithmException | UnsupportedEncodingException | SQLException ex) {
            Logger.getLogger(CadastroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        doDefaultCloseAction();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void DELETARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETARMouseClicked
        ControlUsuario ctrl = new ControlUsuario();
        ctrl.excluir(Integer.parseInt(lb_codigo.getText()));
        dispose();
    }//GEN-LAST:event_DELETARMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DELETAR;
    private javax.swing.JCheckBox cb_admin;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lb_codigo;
    private javax.swing.JTextField lb_login;
    private javax.swing.JTextField lb_nome;
    private javax.swing.JPanel pn_conteudo;
    private javax.swing.JPasswordField pss_senha;
    private javax.swing.JLabel txt_codigo;
    private javax.swing.JLabel txt_login;
    private javax.swing.JLabel txt_nome;
    private javax.swing.JLabel txt_senha;
    // End of variables declaration//GEN-END:variables
}
