/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.usuario;

import control.ControlUsuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre Teixeira
 */
public class ConsultaUsuarios extends javax.swing.JInternalFrame {

    private String[] usuario;
    /**
     * Creates new form CRUD_Usuario
     */
    public ConsultaUsuarios(String[] dados) {
        usuario = dados;
        initComponents();
        inseriLinhaTabela();

    }

    private void inseriLinhaTabela() {
        ControlUsuario control = new ControlUsuario();
        String[][] matriz = control.recuperar();

        DefaultTableModel model_tbl_lista = (DefaultTableModel) jTable1.getModel();
        model_tbl_lista.setNumRows(0);
        for (String[] matriz1 : matriz) {
            model_tbl_lista.addRow(new Object[]{matriz1[0],
                matriz1[1],
                matriz1[2],
                Boolean.parseBoolean(matriz1[4])});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tb_lista = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        NOVO = new javax.swing.JMenu();
        EDITAR = new javax.swing.JMenu();
        PROCURAR = new javax.swing.JMenu();
        DELETAR = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuarios");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/supervisor.png"))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOME", "LOGIN", "ADMINISTRADOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_lista.setViewportView(jTable1);

        jTabbedPane1.addTab("Lista De Usuarios", tb_lista);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        NOVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/add.png"))); // NOI18N
        NOVO.setText("NOVO");
        NOVO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NOVOMouseClicked(evt);
            }
        });
        jMenuBar1.add(NOVO);

        EDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/edit.png"))); // NOI18N
        EDITAR.setText("EDITAR");
        EDITAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EDITARMouseClicked(evt);
            }
        });
        jMenuBar1.add(EDITAR);

        PROCURAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/search.png"))); // NOI18N
        PROCURAR.setText("PROCURAR");
        PROCURAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PROCURARMouseClicked(evt);
            }
        });
        jMenuBar1.add(PROCURAR);

        DELETAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/delete.png"))); // NOI18N
        DELETAR.setText("DELETAR");
        DELETAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETARMouseClicked(evt);
            }
        });
        jMenuBar1.add(DELETAR);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/loop.png"))); // NOI18N
        jMenu1.setText("ATUALIZAR");
        jMenu1.setToolTipText("");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NOVOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NOVOMouseClicked
        CadastroUsuarios tela = new CadastroUsuarios(0, usuario);
        tela.setVisible(true);
        jTabbedPane1.addTab("Cadastro Usuários", tela);
        jTabbedPane1.setSelectedComponent(tela);
    }//GEN-LAST:event_NOVOMouseClicked

    private void EDITARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITARMouseClicked
        DefaultTableModel model_tbl_lista = (DefaultTableModel) jTable1.getModel();
        int selecao = jTable1.getSelectedRow();
        if (selecao != -1) {
            int codigo = Integer.parseInt(model_tbl_lista.getValueAt(selecao, 0).toString());
            CadastroUsuarios tela = new CadastroUsuarios(codigo, usuario);

            tela.setVisible(true);
            jTabbedPane1.addTab("Editando: " + model_tbl_lista.getValueAt(selecao, 1).toString().toUpperCase(), tela);
            jTabbedPane1.setSelectedComponent(tela);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um evento antes de prosseguir");
        }
    }//GEN-LAST:event_EDITARMouseClicked

    private void DELETARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETARMouseClicked
        DefaultTableModel model_tbl_lista = (DefaultTableModel) jTable1.getModel();
        int selecao = jTable1.getSelectedRow();
        int codigo = Integer.parseInt(model_tbl_lista.getValueAt(selecao, 0).toString());
        ControlUsuario ctrl = new ControlUsuario();
        ctrl.excluir(codigo);
    }//GEN-LAST:event_DELETARMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        inseriLinhaTabela();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void PROCURARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PROCURARMouseClicked
        BuscaUsuario tela = new BuscaUsuario();
        tela.setVisible(true);
        jTabbedPane1.add(tela);
//        jTabbedPane1.addTab("Buscando por: " + busca.toUpperCase(), tela);
        jTabbedPane1.setSelectedComponent(tela);
    }//GEN-LAST:event_PROCURARMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DELETAR;
    private javax.swing.JMenu EDITAR;
    private javax.swing.JMenu NOVO;
    private javax.swing.JMenu PROCURAR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tb_lista;
    // End of variables declaration//GEN-END:variables
}
