/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.pessoas;

import control.ControlPessoa;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Andre Teixeira
 */
public class CadastroPessoas extends javax.swing.JInternalFrame {

    private String[] vetor = new String[10];

    /**
     * Creates new form CadastroPessoa
     */
    public CadastroPessoas() {
        initComponents();
    }

    public CadastroPessoas(int codigo) {
        initComponents();
       
        if (codigo == 0) {
            lb_codigo.setText(String.valueOf(codigo));
            DateFormat dateFormat = new SimpleDateFormat("yyyyMMddHHmmss");
            Date date = new Date();
            lb_matricula.setText(dateFormat.format(date));
        } else {
            ControlPessoa controle = new ControlPessoa();
            vetor = controle.recuperar(codigo);

            lb_codigo.setText(vetor[0]);
            lb_nome.setText(vetor[1]);
            lb_cpf.setText(vetor[2]);
            lb_rg.setText(vetor[3]);
            lb_endereco.setText(vetor[4]);
            lb_cidade.setText(vetor[5]);
            lb_telefone.setText(vetor[6]);
            lb_email.setText(vetor[7]);
            lb_matricula.setText(vetor[8]);
        }
        lb_codigo.setEditable(false);
        lb_matricula.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_conteudo = new javax.swing.JPanel();
        txt_codigo = new javax.swing.JLabel();
        lb_codigo = new javax.swing.JTextField();
        txt_nome = new javax.swing.JLabel();
        lb_nome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_cpf = new javax.swing.JLabel();
        lb_cpf = new javax.swing.JTextField();
        txt_rg = new javax.swing.JLabel();
        lb_rg = new javax.swing.JTextField();
        txt_endereco = new javax.swing.JLabel();
        lb_endereco = new javax.swing.JTextField();
        txt_cidade = new javax.swing.JLabel();
        lb_cidade = new javax.swing.JTextField();
        txt_matricula = new javax.swing.JLabel();
        lb_matricula = new javax.swing.JTextField();
        txt_email = new javax.swing.JLabel();
        lb_email = new javax.swing.JTextField();
        txt_telefone = new javax.swing.JLabel();
        lb_telefone = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        DELETAR = new javax.swing.JMenu();

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/person.png"))); // NOI18N

        pn_conteudo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_codigo.setText("CODIGO:");

        txt_nome.setText("* NOME:");

        txt_cpf.setText("CPF");

        lb_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_cpfActionPerformed(evt);
            }
        });

        txt_rg.setText("RG");

        txt_endereco.setText("ENDEREÇO");

        txt_cidade.setText("CIDADE");

        lb_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_cidadeActionPerformed(evt);
            }
        });

        txt_matricula.setText("MATRICULA");

        lb_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_matriculaActionPerformed(evt);
            }
        });

        txt_email.setText("EMAIL");

        txt_telefone.setText("TELEFONE");

        lb_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_telefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_conteudoLayout = new javax.swing.GroupLayout(pn_conteudo);
        pn_conteudo.setLayout(pn_conteudoLayout);
        pn_conteudoLayout.setHorizontalGroup(
            pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pn_conteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_conteudoLayout.createSequentialGroup()
                        .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_telefone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_rg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_rg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                            .addComponent(txt_telefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_conteudoLayout.createSequentialGroup()
                        .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_conteudoLayout.createSequentialGroup()
                                .addComponent(txt_codigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_matricula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_endereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                .addComponent(lb_cpf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_cpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                .addComponent(lb_endereco, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(50, Short.MAX_VALUE))))
        );
        pn_conteudoLayout.setVerticalGroup(
            pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_conteudoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codigo)
                    .addComponent(lb_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nome)
                    .addComponent(lb_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_conteudoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_conteudoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lb_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/save.png"))); // NOI18N
        jMenu1.setText("SALVAR");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/cancel.png"))); // NOI18N
        jMenu2.setText("CANCELAR");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        DELETAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sistema/1x/delete.png"))); // NOI18N
        DELETAR.setText("DELETAR");
        DELETAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DELETARMouseClicked(evt);
            }
        });
        jMenuBar1.add(DELETAR);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_conteudo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_telefoneActionPerformed

    private void lb_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_matriculaActionPerformed

    private void lb_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_cidadeActionPerformed

    private void lb_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_cpfActionPerformed

    private void DELETARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETARMouseClicked
        ControlPessoa ctrl = new ControlPessoa();
        ctrl.excluir(Integer.parseInt(lb_codigo.getText()));
        dispose();
    }//GEN-LAST:event_DELETARMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        ControlPessoa ctrl = new ControlPessoa();

        vetor[0] = lb_codigo.getText();
        vetor[1] = lb_nome.getText();
        vetor[2] = lb_cpf.getText();
        vetor[3] = lb_rg.getText();
        vetor[4] = lb_endereco.getText();
        vetor[5] = lb_cidade.getText();
        vetor[6] = lb_telefone.getText();
        vetor[7] = lb_email.getText();
        vetor[8] = lb_matricula.getText();
        if(vetor[9]==null){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            vetor[9] = sdf.format(Calendar.getInstance().getTime());
        }
            
        ctrl.salvar(vetor);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
       doDefaultCloseAction();
    }//GEN-LAST:event_jMenu2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DELETAR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lb_cidade;
    private javax.swing.JTextField lb_codigo;
    private javax.swing.JTextField lb_cpf;
    private javax.swing.JTextField lb_email;
    private javax.swing.JTextField lb_endereco;
    private javax.swing.JTextField lb_matricula;
    private javax.swing.JTextField lb_nome;
    private javax.swing.JTextField lb_rg;
    private javax.swing.JTextField lb_telefone;
    private javax.swing.JPanel pn_conteudo;
    private javax.swing.JLabel txt_cidade;
    private javax.swing.JLabel txt_codigo;
    private javax.swing.JLabel txt_cpf;
    private javax.swing.JLabel txt_email;
    private javax.swing.JLabel txt_endereco;
    private javax.swing.JLabel txt_matricula;
    private javax.swing.JLabel txt_nome;
    private javax.swing.JLabel txt_rg;
    private javax.swing.JLabel txt_telefone;
    // End of variables declaration//GEN-END:variables
}
